[workspace]

members = ["grax", "grax-algorithms", "grax-core", "grax-query", "grax-impl"]

# [profile.bench]
# opt-level = 3
# debug = true
# rpath = false
# lto = true
# debug-assertions = false
# codegen-units = 1
