[package]
name = "grax-dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cap-std = "2.0.0"
grax-core = { path = "../grax-core" }
