[package]
name = "grax-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ambassador = "0.3.5"
# auto-delegate = "0.0.9"
# delegate = "0.10.0"
# hereditary = "0.1.0"

[features]
extensive = []
